language: python
python:
  - 3.7
dist: xenail
sudo: required
notifications:
  email:
    recipients:
    - chris+manowar_agent@halbersma.us
  on_success: always
  on_failure: always
before_script:
- echo "pre_build"
- "./travis/pre_build.sh"
- export DEBIAN_FRONTEND=noninteractive; sudo -E apt-get -y  install python3-pip python-dev openjdk-8-jre
- sudo pip3 install --upgrade setuptools
- sudo pip3 install -r requirements.txt
script:
- "./travis/testing.sh"
after_success:
- "./travis/package.sh"
before_install:
- pwd

