language: python
cache: pip
python:
- 3.6
- 3.7
- 3.5
dist: xenail
sudo: required
notifications:
  email:
    recipients:
    - chris+manowar_agent@halbersma.us
  on_success: always
  on_failure: always
before_script:
- echo "pre_build"
- "./travis/pre_build.sh"
- export DEBIAN_FRONTEND=noninteractive; sudo -E apt-get -y  install python3-pip python-dev
  openjdk-8-jre
- pip3 install --upgrade setuptools
- pip3 install -r requirements.txt
script:
- "./travis/testing.sh"
after_success:
- "./travis/packages.sh"
before_install:
- pwd
env:
  global:
  - secure: jl25Yev0ncg75ZEohOyEl5t3YCsZCVnlXZi3wts85TEYQS0NdGlF2PVQw1VGRzrkk9ryRBmVLygjJoxnkLwdUKn0wcuERriCFBrOJkgiet1vc/5sDm89CC6ZFELlUOvLxBoA/ZRP6X+zFbFBf5Ewpm1idzviShRCoPLd/1pjthi3UNaL+kFZUANtTNSm8+cM6lCin6dvY96C2BvewTSZv3eAgmuAdruT1BBQLr+Y7kvHvTAxW83I7k/eYNk8AQz28lzbGlI6W/0PeXjYCbyH2lyw5oELl5ImtaUaFVOUvqnG/GZuXUzuwyXGYHmGVjV2VrotNE/JnORxzNc6j4IJtQpMvk9RDhTSEwls7tS6BCakXAVJAG8+NOcyGcPVztVyyf7fDVR4S1B5PLYpbMYaPea9M/FjbWG3Wyqj3Ywau+VgKTzXlG8yTsWqiO0/QqPIaGKxv2JhzttA98Vr0LsWridiGIGRri+fkW5zHzBK4wOpnVAiEndxHKP94JanWMfPLAIqpF/Ypq3XEiLA3sSiprG5eYgUGV+NxlVR6tRkPPrM/Sd/zrqBWL8Ls40akoDYKdMK++6KnPA+0DvRHYJTDWtAjxKFonVG5jlJL1uuPmXgqDvVYB2tPLwi7aBJS/CHq7+hcK6TOcTICuPfQcbwat2WFPB0SfuTqOBJquCE1bM=
  - secure: nnGL9jhFtjcsp7YenxZlyxfubC5FsSGtMkjMD/jTP/msPcK0Us1F4ysYsRUhbDptx21CPjCNv2ecKQMfAqTFEjnnJGm9iODEOl+OsWvXVBfJvlqNPJ9DDOYmPpl3QOFOE6sbWVGSEtvp6n41MbrnyzDsF1YilDz7OxJ9j3f3kRm2C24C8SPDnqQL1QsDMC7UFLg4n7on3zpWbblJ9JmNvCoadR+T3EbJTYfvf+x26gjpKoYqpiTGuopK474QpvP3KadUr2azYXU8IqJsv4KrcSl1sPR7wTmTgVqua8Cn4810/Y/5LJOdeS8kxxOlHPCcpEfCAPSV4fTsOL7ef8VKRwuNpIpdKnwcemNEey06jjjC7Nx7pxV21OGX08JXWK7jwymF0GeNdZ6uNZHwvD38PCEUxJDuSZv3pUHVVgTqsZM48BMIUX9NELmqOB+HDOgdAr0TdVE27/YT7j3f+npD6M+8PHYes01NYhCoorq2lllU/v4e4iqOosjZ8WcNf90kTDEN/yKnt6h+t9zI3eCDZ52nSj17U10Hs1G899FaYisFzcMyNMWX2IK29dmEv3CUgfPoI0eGiEsVORqdWTUBhnBU8COrKkFGwjSwMY1XbPxvGnbiOZ3iyp/YlunEy1Fd6zne+9I+oasc1efXibeOsFjSIS+7ujHDGhLUM1ghKL0=
