language: python
python:
- 3.6
dist: xenail
sudo: required
notifications:
  email:
    recipients:
    - chris+manowar_agent@halbersma.us
  on_success: always
  on_failure: always
before_script:
- echo "pre_build"
- "./travis/pre_build.sh"
- export DEBIAN_FRONTEND=noninteractive; sudo -E apt-get -y  install python3-pip python-dev
  openjdk-8-jre
- sudo pip3 install --upgrade setuptools
- sudo pip3 install -r requirements.txt
script:
- "./travis/testing.sh"
after_success:
- "./travis/packages.sh"
before_install:
- pwd
env:
  global:
  - secure: U/nsGwKOjO4lx+a+gsi6ZZ1898UjS9F/nw5SpLOhTDe/WWCpSz9rYLWLrXS0BNnAoBMtJ+aaGZ/MeVBueINGDaAO/0R/KysOWigqxmP+SaXJtgGekwsbhomEVWo1wMCpQ9svxwRbx9eeSNMEHICjtkzT+FeS7X1cXGiD6A97YD5qxzZzE5Vrr5N9Y+6WGf5fH0HvTJpHyoM4WMK9BGnHuEtK5n0cjvut9/R8NVxWQJ+6hnbdDQy5SFRannlw38WJqt3pejE4ODh+2qFde5aiooYe+03Gt8kivVR1Zmkj2tDvYU1ORx2iLiFZInJlpZNFZxkswxzFbEAsWiwDIGbIeJfV9D/D9ZFsBi/nfASfr+6yosiRm/QfXE8B057a0wuKnH7iwkGNqLSl8Nk3oemScmsik36GxLWjcDMCaJ/0d88Y1Eu/k/GcZ4cgBZrmU5mSm6drcg2iJYLp4SCch16VOo8fUtUCWLlRyOhFiY+wy+swhkdREYnzeTn+OY2GEhChtU5KYrCYssLhita60VD4wJbe4nhLPbpSpagSPa7tSZWNPOCPTnegVkdA8zch9+U0MM4lE5xVACarlSNePyW7h+yhUS4Zd1hbVBAGIKbpriCMtxhjq28fWWeIl4aOm0s+4L/4lg8A4GWvaNjIklwChgCof8cZTnnND6pcBgr6NdA=
  - secure: aDIJq41wH/Qgug5/ekUTCrQcT7ANdoT0oBKPIOuFkaW670/Mo27RmCFMVcY3XC1aokZNFwDat4nSBplLLwF6uIuEb+XsU2cLpXGK+CH2HZbKnDL4/QRx4HrfOLIOq712K98hRvnrAd0rdmpfMNcnZRrktEMUZ6+THD5MkkZDPDo8oQQ8EzMb/hbC10vmsslDV8BNKjZBLrRsbESUB7kzwRuYRCUpiaHe9PP2rm/xrokj4WeYDvtNxlnJRcvFMbzvB2tWfBK7t2oqA24yrKdSKI+eACBcnoUw+M8Sm9nFRr6fdQPFf/p2O53xI4Tyi8V4fQRdrahSrn+zoXt0EebSLEUHjK/Y0KqMN/eqs7KMpaToE9toLNGVHcZgmplEylm6+DnugOd1imXQ/ZExW37AgtaTA/Vs8HYBg+QeEV4tX2MJYsK/ZbVLvWy091Z/oHB6oh2hBBtZV2EyJzaK1tmmzyLX3jQzt6ejybPTkCCMc0HAhAtAMi6pTtwGFGpHwfYRemCKx/9oOqUUEqnTmiOcsx2PX6tW4J6xT5xmsQ6OTHVNVzjCrRWqaAlb9m4HrhyrtgTJSQFBYmSDKwh2ZWmnhrbNRd3tqj/aME1bJtQLzyOYWpsreXKgkuf/e8VYhIbStpHinQiHfnNPqvx+2VdP/I931zMwA5Wu4GdVZe1BnCY=
