name: manowar-agent # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: An attempt to make a Snap of the Manowar Agent # 79 char long summary
description: |
  Manowar Agent Collects a Jsonic representation of the host it is ran on
  and has the ability to report that representation back to an web endpoint
  for further processing

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  manowar-agent:
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - automake
      - autoconf
      - libtool
      - git
      - libzbar-dev
      - libzbar0
      - python3-dev
      - salt-minion
      - dpkg
      - jq
    python-packages:
      - certifi
      - pylint
      - chardet
      - idna
      - Jinja2
      - jq
      - MarkupSafe
      - msgpack
      - pycrypto
      - PyYAML
      - pyzmq
      - requests
      - tornado
      - urllib3
      - virtualenv
      - virtualenv-clone
      - virtualenv-tools
      - bandit
      - twine

apps:
  manowar-agent:
    command: bin/manowar_agent
    plugs: [hardware-observe, log-observe, mount-observe, network-observe, network-setup-observe, physical-memory-observe, system-observe, upower-observe]
