name: manowar-agent # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: An attempt to make a Snap of the Manowar Agent # 79 char long summary
description: |
  Manowar Agent Collects a Jsonic representation of the host it's ran on
  and has the ability to report that representation back to an web endpoint
  for further processing

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  manowar-agent:
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - autoconf
      - libtool
      - git
    python-packages:
      - certifi
      - pylint
      - chardet
      - idna
      - Jinja2
      - jq
      - MarkupSafe
      - msgpack
      - pycrypto
      - PyYAML
      - pyzmq
      - requests
      - salt
      - tornado
      - urllib3
      - virtualenv
      - virtualenv-clone
      - virtualenv-tools
      - bandit
      - twine
